"""API First: every call the web UI makes is a documented OpenAPI operation.

Scans src/web for `/v1/...` URLs (template placeholders become wildcards) and checks each
against the OpenAPI document the API publishes. Run as a script to print the UI -> API map:

    python tests/api/test_api_first.py > docs/UI-API-MAP.md
"""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

WEB = Path(__file__).resolve().parents[2] / "src" / "web"
URL = re.compile(r"/v1/[^\"'`\s)]*")
PLACEHOLDER = re.compile(r"\$\{[^}]*\}")
METHOD = re.compile(r"method:\s*\"(GET|POST|PUT|PATCH|DELETE)\"")
BASE = re.compile(r"const (\w+) = `(/v1/[^`]*)`")


def ui_calls() -> dict[str, set[tuple[str, str]]]:
    """path template -> {(file, method)}"""
    calls: dict[str, set[tuple[str, str]]] = defaultdict(set)
    for f in list(WEB.glob("app/**/*.ts*")) + list(WEB.glob("components/**/*.ts*")) + list(WEB.glob("lib/**/*.ts*")):
        text = f.read_text(encoding="utf-8")
        # Expand local URL prefixes, e.g. const base = `/v1/events/${slug}` used as `${base}/comments`.
        for name, value in BASE.findall(text):
            text = text.replace("${" + name + "}", value)
        for m in URL.finditer(text):
            if text[m.start() - 1] not in "\"'`":  # a string literal, not prose that mentions a path
                continue
            raw = PLACEHOLDER.sub("{x}", m.group(0)).split("?")[0].rstrip("/.,;")
            raw = re.sub(r"\$\{[^/]*$", "{x}", raw)  # a placeholder cut off by the regex end
            if raw.endswith("/v1") or raw == "/v1/":
                continue
            window = text[m.end(): m.end() + 160]
            method = METHOD.search(window)
            calls[raw].add((str(f.relative_to(WEB)).replace("\\", "/"), method.group(1) if method else "GET"))
    return calls


def _matches(ui: str, api: str) -> bool:
    ui_segments, api_segments = ui.strip("/").split("/"), api.strip("/").split("/")
    if len(ui_segments) != len(api_segments):
        return False
    for u, a in zip(ui_segments, api_segments, strict=True):
        pattern = "^" + re.sub(r"\\\{[^}]*\\\}", "[^/]+", re.escape(a)) + "$"
        if not re.match(pattern, u.replace("{x}", "X")):
            return False
    return True


def resolve(ui: str, spec_paths: dict, method: str = "GET") -> str | None:
    """Most literal matching path that supports the method (so /records/verify beats /records/{id})."""
    hits = sorted((p for p in spec_paths if _matches(ui, p)), key=lambda p: p.count("{"))
    return next((p for p in hits if method.lower() in spec_paths[p]), hits[0] if hits else None)


def test_every_ui_call_is_a_documented_operation(client):
    spec_paths = client.get("/openapi.json").json()["paths"]
    calls = ui_calls()
    assert len(calls) > 30, "scanner found suspiciously few API calls"
    problems = []
    for ui, uses in sorted(calls.items()):
        for _, method in uses:
            path = resolve(ui, spec_paths, method)
            if path is None or method.lower() not in spec_paths[path]:
                problems.append(f"{method} {ui}")
    assert problems == [], f"UI calls with no documented operation: {problems}"


if __name__ == "__main__":
    import json
    import os
    import sys

    os.environ.update(DATABASE_URL="sqlite+pysqlite:///:memory:", SEED_ON_BOOT="false", MINIO_ENDPOINT="", WEBHOOK_WORKER="false")
    sys.path.insert(0, str(WEB.parent / "api"))
    from app.main import app

    spec = json.loads(json.dumps(app.openapi()))
    paths = spec["paths"]
    sys.stdout.reconfigure(encoding="utf-8")
    print("# UI → API map")
    print()
    print("Generated by `python tests/api/test_api_first.py`. Every `/v1/...` call in `src/web`, the file that makes it, and the documented OpenAPI operation it resolves to. `tests/api/test_api_first.py` fails if any call has no operation.")
    print()
    print("| Method | Operation | Summary | Called from |")
    print("| --- | --- | --- | --- |")
    rows = []
    for ui, uses in ui_calls().items():
        for method in sorted({m for _, m in uses}):
            path = resolve(ui, paths, method)
            op = spec["paths"].get(path, {}).get(method.lower(), {})
            files = sorted({f for f, m in uses if m == method})
            rows.append((path or f"MISSING {ui}", method, op.get("summary", ""), files))
    for path, method, summary, files in sorted(rows):
        print(f"| {method} | `{path}` | {summary} | {', '.join(f'`{f}`' for f in files)} |")
    used = {r[0] for r in rows}
    print()
    print(f"{len(used)} of the {len(paths)} documented paths are used by the UI. The rest are API-only: " + ", ".join(f"`{p}`" for p in sorted(set(paths) - used)) + ".")
