"""baseline

Revision ID: 2ecc1fd5f0ae
Revises: 
Create Date: 2026-09-28 13:59:56.231994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ecc1fd5f0ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_event_id'), 'audit_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_audit_events_seq'), 'audit_events', ['seq'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=280), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submissions_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submissions_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('judging_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voting_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voting_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results_published', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('judging_mode', sa.String(length=20), nullable=False),
    sa.Column('voting_access', sa.String(length=30), nullable=False),
    sa.Column('vote_mode', sa.String(length=30), nullable=False),
    sa.Column('reviews_per_project', sa.Integer(), nullable=False),
    sa.Column('quadratic_budget', sa.Integer(), nullable=False),
    sa.Column('max_team_size', sa.Integer(), nullable=False),
    sa.Column('require_verified_email', sa.Boolean(), nullable=False),
    sa.Column('widget_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('widget_token')
    )
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_event_id'), 'api_keys', ['event_id'], unique=False)
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_table('assignment_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reviews_per_project', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_batches_event_id'), 'assignment_batches', ['event_id'], unique=False)
    op.create_table('ballots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('voter_key', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('order', sa.JSON(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'voter_key', name='uq_event_voter')
    )
    op.create_index(op.f('ix_ballots_event_id'), 'ballots', ['event_id'], unique=False)
    op.create_index(op.f('ix_ballots_token'), 'ballots', ['token'], unique=True)
    op.create_table('custom_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_questions_event_id'), 'custom_questions', ['event_id'], unique=False)
    op.create_table('email_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    op.create_table('event_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_user_role')
    )
    op.create_index(op.f('ix_event_roles_event_id'), 'event_roles', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_roles_role'), 'event_roles', ['role'], unique=False)
    op.create_index(op.f('ix_event_roles_user_id'), 'event_roles', ['user_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_event_id'), 'import_jobs', ['event_id'], unique=False)
    op.create_table('judge_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('track_ids', sa.JSON(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_judge_invites_event_id'), 'judge_invites', ['event_id'], unique=False)
    op.create_table('normalization_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalization_runs_event_id'), 'normalization_runs', ['event_id'], unique=False)
    op.create_table('pairwise_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('ranking', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairwise_runs_event_id'), 'pairwise_runs', ['event_id'], unique=False)
    op.create_table('rubrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scale_min', sa.Integer(), nullable=False),
    sa.Column('scale_max', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('signed_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signed_records_event_id'), 'signed_records', ['event_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_event_id'), 'teams', ['event_id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'slug', name='uq_event_track_slug')
    )
    op.create_index(op.f('ix_tracks_event_id'), 'tracks', ['event_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_event_id'), 'webhooks', ['event_id'], unique=False)
    op.create_table('criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rubric_id', 'key', name='uq_rubric_criterion_key')
    )
    op.create_index(op.f('ix_criteria_rubric_id'), 'criteria', ['rubric_id'], unique=False)
    op.create_table('invite_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_links_team_id'), 'invite_links', ['team_id'], unique=False)
    op.create_index(op.f('ix_invite_links_token'), 'invite_links', ['token'], unique=True)
    op.create_table('judge_tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['event_roles.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'track_id', name='uq_judge_track')
    )
    op.create_index(op.f('ix_judge_tracks_role_id'), 'judge_tracks', ['role_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_member'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_user')
    )
    op.create_index(op.f('ix_memberships_event_id'), 'memberships', ['event_id'], unique=False)
    op.create_index(op.f('ix_memberships_team_id'), 'memberships', ['team_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('prizes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prizes_event_id'), 'prizes', ['event_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('demo_video_url', sa.String(length=500), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('live_link', sa.String(length=500), nullable=False),
    sa.Column('tech_tags', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_event_id'), 'submissions', ['event_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_team_id'), 'submissions', ['team_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('webhook_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_next_attempt_at'), 'webhook_deliveries', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('judge_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['assignment_batches.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'judge_id', 'submission_id', name='uq_event_judge_project')
    )
    op.create_index(op.f('ix_assignments_batch_id'), 'assignments', ['batch_id'], unique=False)
    op.create_index(op.f('ix_assignments_event_id'), 'assignments', ['event_id'], unique=False)
    op.create_index(op.f('ix_assignments_judge_id'), 'assignments', ['judge_id'], unique=False)
    op.create_index(op.f('ix_assignments_submission_id'), 'assignments', ['submission_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_event_id'), 'comments', ['event_id'], unique=False)
    op.create_index(op.f('ix_comments_submission_id'), 'comments', ['submission_id'], unique=False)
    op.create_table('custom_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['custom_questions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_answers_submission_id'), 'custom_answers', ['submission_id'], unique=False)
    op.create_table('eligibility_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('blocks_judging', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_flags_submission_id'), 'eligibility_flags', ['submission_id'], unique=False)
    op.create_table('normalized_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('n_reviews', sa.Integer(), nullable=False),
    sa.Column('raw_mean', sa.Float(), nullable=False),
    sa.Column('adjusted', sa.Float(), nullable=False),
    sa.Column('std_error', sa.Float(), nullable=False),
    sa.Column('raw_rank', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('rank_delta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['normalization_runs.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_scores_run_id'), 'normalized_scores', ['run_id'], unique=False)
    op.create_index(op.f('ix_normalized_scores_submission_id'), 'normalized_scores', ['submission_id'], unique=False)
    op.create_table('pairwise_comparisons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('judge_id', sa.Uuid(), nullable=False),
    sa.Column('winner_id', sa.Uuid(), nullable=False),
    sa.Column('loser_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loser_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairwise_comparisons_event_id'), 'pairwise_comparisons', ['event_id'], unique=False)
    op.create_index(op.f('ix_pairwise_comparisons_judge_id'), 'pairwise_comparisons', ['judge_id'], unique=False)
    op.create_table('submission_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_assets_submission_id'), 'submission_assets', ['submission_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ballot_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ballot_id', 'submission_id', name='uq_ballot_project')
    )
    op.create_index(op.f('ix_votes_ballot_id'), 'votes', ['ballot_id'], unique=False)
    op.create_index(op.f('ix_votes_event_id'), 'votes', ['event_id'], unique=False)
    op.create_index(op.f('ix_votes_submission_id'), 'votes', ['submission_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('judge_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('raw_weighted', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judge_id', 'submission_id', name='uq_judge_submission_score')
    )
    op.create_index(op.f('ix_scores_assignment_id'), 'scores', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_scores_event_id'), 'scores', ['event_id'], unique=False)
    op.create_index(op.f('ix_scores_judge_id'), 'scores', ['judge_id'], unique=False)
    op.create_index(op.f('ix_scores_submission_id'), 'scores', ['submission_id'], unique=False)
    op.create_table('score_cells',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('score_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_id', 'criterion_id', name='uq_score_criterion')
    )
    op.create_index(op.f('ix_score_cells_score_id'), 'score_cells', ['score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_cells_score_id'), table_name='score_cells')
    op.drop_table('score_cells')
    op.drop_index(op.f('ix_scores_submission_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_judge_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_event_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_assignment_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_votes_submission_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_event_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_ballot_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_submission_assets_submission_id'), table_name='submission_assets')
    op.drop_table('submission_assets')
    op.drop_index(op.f('ix_pairwise_comparisons_judge_id'), table_name='pairwise_comparisons')
    op.drop_index(op.f('ix_pairwise_comparisons_event_id'), table_name='pairwise_comparisons')
    op.drop_table('pairwise_comparisons')
    op.drop_index(op.f('ix_normalized_scores_submission_id'), table_name='normalized_scores')
    op.drop_index(op.f('ix_normalized_scores_run_id'), table_name='normalized_scores')
    op.drop_table('normalized_scores')
    op.drop_index(op.f('ix_eligibility_flags_submission_id'), table_name='eligibility_flags')
    op.drop_table('eligibility_flags')
    op.drop_index(op.f('ix_custom_answers_submission_id'), table_name='custom_answers')
    op.drop_table('custom_answers')
    op.drop_index(op.f('ix_comments_submission_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_event_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_assignments_submission_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_judge_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_event_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_batch_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_next_attempt_at'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_submissions_team_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_event_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_prizes_event_id'), table_name='prizes')
    op.drop_table('prizes')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_team_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_event_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_judge_tracks_role_id'), table_name='judge_tracks')
    op.drop_table('judge_tracks')
    op.drop_index(op.f('ix_invite_links_token'), table_name='invite_links')
    op.drop_index(op.f('ix_invite_links_team_id'), table_name='invite_links')
    op.drop_table('invite_links')
    op.drop_index(op.f('ix_criteria_rubric_id'), table_name='criteria')
    op.drop_table('criteria')
    op.drop_index(op.f('ix_webhooks_event_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_tracks_event_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_teams_event_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_signed_records_event_id'), table_name='signed_records')
    op.drop_table('signed_records')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_pairwise_runs_event_id'), table_name='pairwise_runs')
    op.drop_table('pairwise_runs')
    op.drop_index(op.f('ix_normalization_runs_event_id'), table_name='normalization_runs')
    op.drop_table('normalization_runs')
    op.drop_index(op.f('ix_judge_invites_event_id'), table_name='judge_invites')
    op.drop_table('judge_invites')
    op.drop_index(op.f('ix_import_jobs_event_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_event_roles_user_id'), table_name='event_roles')
    op.drop_index(op.f('ix_event_roles_role'), table_name='event_roles')
    op.drop_index(op.f('ix_event_roles_event_id'), table_name='event_roles')
    op.drop_table('event_roles')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_custom_questions_event_id'), table_name='custom_questions')
    op.drop_table('custom_questions')
    op.drop_index(op.f('ix_ballots_token'), table_name='ballots')
    op.drop_index(op.f('ix_ballots_event_id'), table_name='ballots')
    op.drop_table('ballots')
    op.drop_index(op.f('ix_assignment_batches_event_id'), table_name='assignment_batches')
    op.drop_table('assignment_batches')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_event_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_audit_events_seq'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
